# All config files should have a "Default" section, although section is ignored in this file
# See the Sydor wiki under xpad:gencorr

[Default]
[ImageParams]
asic_width = 128
asic_height = 128
img_width = 512
img_height = 512
num_caps = 8

#Keck
file_offset = 256
file_gap = 1024
bpp = 16

##MMPAD
##file_offset = 256
##file_gap = 2048
##bpp = 32

[Sensor Params]
# How many images at the start of a run to skip
num_skip_images = 2
# Numbering is left-to-right, top-to-bottom
# Keck020 (LLNL)[1, 0, 0, 0; 0, 0, 0, 0; 0, 0, 0, 0; 1, 0, 0, 0]
bad_asics = [0, 0, 0, 0; 0, 0, 0, 0; 0, 0, 0, 0; 0, 0, 0, 0]
#bad_asics = [0 0 0 0 0 0 0 0; 0 0 0 0 0 0 0 0; 0 0 0 0 0 0 0 0; 0 0 0 0 0 0 0 0]
[Analysis Params]
#hot_iqr_thresh and dark_iqr_thresh are actually Z-scores i.e. sigmas to clip at
hot_iqr_thresh = [3.73 3.83 3.9 4 4.1 4.2 4.3 4.4 3.83]
dark_iqr_thresh = [3.73 3.83 4 4.2 4.4 3.83]
#dark_slope_thresh = [0.9 0.55 0.5]
dark_slope_thresh = [3 4 5]
hot_slope_thresh = [3 4 5]


# An image of pixels that are *a priori* bad e.g. a disconnected tap, or that bad column in formerly SMK020
prelim_bad_filename = blank_bad.pgm
#dark_image_filename = /mnt/raid/airbox_char/set-25JAN2024/run-flatfield5ms-back-2/frames/flatfield5ms-back-2_00000001.raw
#bright_image_filename = /mnt/raid/airbox_char/set-25JAN2024/run-flatfield5ms-fore-2/frames/flatfield5ms-fore-2_00000001.raw

dark_image_filename = aps10-20260311/set-ee_11mar26_ff/run-B20_1/frames/B20_1_00000001.raw
bright_image_filename = aps10-20260311/set-ee_11mar26_ff/run-F20_1/frames/F20_1_00000001.raw
#bright_image_filename = run-ff1/frames/ff1_00000001.raw
#dark_image_filename = set-Factory_Testing_30JAN/run-RN_200_500/frames/big_readnoise.raw
#bright_image_filename = set-Factory_Testing_30JAN/run-RN_200_500/frames/big_readnoise.raw
#read_noise_filename=trial_readnoise.raw

