# All config files should have a "Default" section, although section is ignored in this file
# See the Sydor wiki under xpad:sensorchar

[Default]
asic_width = 128
asic_height = 128
img_width = 512
img_height = 512
num_caps = 1

#Keck
#file_offset = 256
#file_gap = 1024
#bpp = 16

##MMPAD
file_offset = 256
file_gap = 2048
bpp = 32

sys_type = mmpad

[Sensor]
# How many images at the start of a run to skip
num_skip_images = 0

[Analysis]
trim_pixels = 128
asic_start_y = 128
asic_start_x = 128
margin = 2


#bg_image_filename = set-24-04-10_Debounce/run-bg-1ms/frames/bg_00000001.raw
#fg_image_filename = set-24-04-10_Debounce/run-fg-1ms/frames/fg-1ms_00000001.raw

#bg_image_filename = set-MMPAD_OCT2023/run-1frm_si_04_000016/frames/1frm_si_04_000016_00000001.raw
#fg_image_filename = set-MMPAD_OCT2023/run-1frm_si_04_000014/frames/1frm_si_04_000014_00000001.raw

#bg_image_filename = set-ID7B2_Oct2023/run-720frm_sucrose_09_1pct_01/frames/720frm_sucrose_09_1pct_01_00000001.raw
#fg_image_filename = set-ID7B2_Oct2023/run-720frm_sucrose_09_100pct_02/frames/720frm_sucrose_09_100pct_02_00000001.raw

bg_image_filename = set-ID7B2_Oct2023/run-1000frm_ruby_02_0p15pct_03/frames/1000frm_ruby_02_0p15pct_03_00000001.raw
fg_image_filename = set-ID7B2_Oct2023/run-720frm_ruby_02_0p15pct_02/frames/720frm_ruby_02_0p15pct_02_00000001.raw 

# The bad pixel masks
dark_mask = dark_pixels.pgm
hot_mask = hot_pixels.pgm

fit_max_eval = 200000
out_name = db_image.raw