# All config files should have a "Default" section, although section is ignored in this file
# See the Sydor wiki under xpad:sensorchar

[Default]
[ImageParams]
asic_width = 128
asic_height = 128
img_width = 512
img_height = 512
num_caps = 8

#Keck
file_offset = 256
file_gap = 1024
bpp = 16

##MMPAD
#file_offset = 256
#file_gap = 2048
#bpp = 32

[Sensor Params]
# How many images at the start of a run to skip
num_skip_images = 2

[Analysis Params]
x_margin = 14
y_margin = 14

dark_image_filename = /mnt/raid/mmpad/set-vac/run-dark_100us_integ_15us_interf/frames/dark_100us_integ_15us_interf_00000001.raw
bright_image_filename = /mnt/raid/mmpad/set-vac/run-dark_10ms_integ_15us_interf/frames/dark_10ms_integ_15us_interf_00000001.raw

start_time = 100e-6
end_time = 10e-3

exp_time = [500e-9 1e-3 2e-3 4e-3 8e-3 16e-3]
temperature = 15
#exp_time = [500e-9 1e-6 10e-6 100e-6 1e-3 10e-3]
#temperature = 15

dark_image_filename = set-Factory_Testing_30JAN/run-DC_Back_500ns/frames/DC_Back_500ns_00000001.raw
bright_image_filename=set-Factory_Testing_30JAN/run-DC_1us/frames/DC_1us_00000001.raw;set-Factory_Testing_30JAN/run-DC_10us/frames/DC_10us_00000001.raw;set-Factory_Testing_30JAN/run-DC_100us/frames/DC_100us_00000001.raw;set-Factory_Testing_30JAN/run-DC_1ms/frames/DC_1ms_00000001.raw;set-Factory_Testing_30JAN/run-DC_10ms/frames/DC_10ms_00000001.raw

dark_image_filename=set-Factory_Testing_30JAN/run-DC_500ns_WT5/frames/DC_500ns_WT5_00000001.raw
bright_image_filename=set-Factory_Testing_30JAN/run-DC_10us_WT5/frames/DC_10us_WT5_00000001.raw;set-Factory_Testing_30JAN/run-DC_100us_WT5/frames/DC_100us_WT5_00000001.raw;set-Factory_Testing_30JAN/run-DC_1ms_WT5/frames/DC_1ms_WT5_00000001.raw;set-Factory_Testing_30JAN/run-DC_10ms_WT5/frames/DC_10ms_WT5_00000001.raw

dark_image_filename=set-FactoryTesting_10FEB2025B/run-BG_RN_500_200B/frames/BG_RN_500_200B_00000001.raw
bright_image_filename=set-FactoryTesting_10FEB2025B/run-DC_100us_200ns_BiasOnThisTime/frames/DC_100us_200ns_BiasOnThisTime_00000001.raw;set-FactoryTesting_10FEB2025B/run-DC_1ms_200ns_BiasOnThisTime/frames/DC_1ms_200ns_BiasOnThisTime_00000001.raw;set-FactoryTesting_10FEB2025B/run-DC_10ms_200ns_BiasOnThisTime/frames/DC_10ms_200ns_BiasOnThisTime_00000001.raw;set-FactoryTesting_10FEB2025B/run-DC_100ms_200ns_BiasOnThisTime/frames/DC_100ms_200ns_BiasOnThisTime_00000001.raw

dark_image_filename=set-FactoryTesting_10FEB2025B/run-BG_RN_500_200B/frames/BG_RN_500_200B_00000001.raw
bright_image_filename=set-FactoryTesting_10FEB2025B/run-DC_100us_200ns_BOTT_WT15/frames/DC_100us_200ns_BOTT_WT15_00000001.raw;set-FactoryTesting_10FEB2025B/run-DC_1ms_200ns_BOTT_WT15/frames/DC_1ms_200ns_BOTT_WT15_00000001.raw;set-FactoryTesting_10FEB2025B/run-DC_10ms_200ns_BOTT_WT15/frames/DC_10ms_200ns_BOTT_WT15_00000001.raw;set-FactoryTesting_10FEB2025B/run-DC_100ms_200ns_BOTT_WT15/frames/DC_100ms_200ns_BOTT_WT15_00000001.raw

dark_image_filename=aps10-20260311/set-ee_11mar2026_RN/run-run1/frames/run1_00000001.raw
bright_image_filename=aps10-20260311/set-ee_11mar2026_DC/run-run1_1ms/frames/run1_1ms_00000001.raw;aps10-20260311/set-ee_11mar2026_DC/run-run2_2ms/frames/run2_2ms_00000001.raw;aps10-20260311/set-ee_11mar2026_DC/run-run3_4ms/frames/run3_4ms_00000001.raw;aps10-20260311/set-ee_11mar2026_DC/run-run4_8ms/frames/run4_8ms_00000001.raw;aps10-20260311/set-ee_11mar2026_DC/run-run5_16ms/frames/run5_16ms_00000001.raw

# A list of all the ASICs populated e.g. SMK, used for output results
asics_in_use = [3 4]
# If using a full array for Keck or MMPAD, you can use
asics_in_use = 1:16

# The bad pixel masks
dark_mask = aps10-corr-20260311/standard/dark_pixels.pgm
hot_mask = aps10-corr-20260311/standard/hot_pixels.pgm