# All config files should have a "Default" section, although section is ignored in this file

[Default]
[ImageParams]
asic_width = 128
asic_height = 128
img_width = 512
img_height = 512
num_caps = 8

#Keck
file_offset = 256
file_gap = 1024
bpp = 16

##MMPAD
#file_offset = 256
#file_gap = 2048
#bpp = 32

[Sensor Params]
#How many images at the start of a run to skip
num_skip_images = 2

[Analysis Params]
gain_threshold = 0.001

# Edge pixels to ignore for analysis, not map calculation
x_margin = 3
y_margin = 3

#Background File
dark_image_filename = aps10-20260311/set-ee_11mar26_ff/run-B50_1/frames/B50_1_00000001.raw
#Foreground File
bright_image_filename = aps10-20260311/set-ee_11mar26_ff/run-F50_1/frames/F50_1_00000001.raw

# Keck llnl020
#dark_image_filename = /home/sydor/projects/PAD_Analysis2/run-feb-26-2024-bg-geocor-pinhole-3/frames/feb-26-2024-bg-geocor-pinhole-3_00000001.raw
#bright_image_filename = /home/sydor/projects/PAD_Analysis2/run-feb-26-2024-ff-fg-3/frames/feb-26-2024-ff-fg-3_00000001.raw

# Kegapad  IHEP Test Only
#dark_image_filename =  Z:\PRODUCTS\XRAY\KeckPAD\IHEP_Testing\run-tuesday10_bg\frames\tuesday10_bg_00000001.raw
#bright_image_filename = Z:\PRODUCTS\XRAY\KeckPAD\IHEP_Testing\run-tuesday11\frames\tuesday11_00000001.raw

#dark_image_filename = run-bg_xray_20ms_200ns/frames/bg_xray_20ms_200ns_00000001.raw
#bright_image_filename = big_flatfield.raw

diff_image_filename = moving_flat_caps.raw


# Mask files generated by a previous program
dark_mask = Z:\PRODUCTS\XRAY\KeckPAD\IHEP_Testing\dark_pixels.pgm
hot_mask = Z:\PRODUCTS\XRAY\KeckPAD\IHEP_Testing\hot_pixels.pgm

dark_mask = dark_pixels.pgm
hot_mask = hot_pixels.pgm

