# All config files should have a "Default" section, although section is ignored in this file

[Default]
[ImageParams]
asic_width = 128
asic_height = 128
img_width = 1024
img_height = 512
num_caps = 1

#Keck
file_offset = 256
file_gap = 1024
bpp = 16

##MMPAD
#file_offset = 256
#file_gap = 2048
#bpp = 32

[Sensor Params]
#How many images at the start of a run to skip
num_skip_images = 2

[Analysis Params]
gain_threshold = 0.001

# Edge pixels to ignore for analysis, not map calculation
x_margin = 3
y_margin = 3

#Background File
dark_image_filename = run-bg_Cap0/frames/bg_Cap0_00000001.raw
#Foreground File
bright_image_filename = run-fg_Cap0/frames/fg_halfaa

# Keck llnl020
#dark_image_filename = /home/sydor/projects/PAD_Analysis2/run-feb-26-2024-bg-geocor-pinhole-3/frames/feb-26-2024-bg-geocor-pinhole-3_00000001.raw
#bright_image_filename = /home/sydor/projects/PAD_Analysis2/run-feb-26-2024-ff-fg-3/frames/feb-26-2024-ff-fg-3_00000001.raw

# Kegapad  IHEP Test Only
dark_image_filename =  Z:\PRODUCTS\XRAY\KeckPAD\IHEP_Testing\run-tuesday10_bg\frames\tuesday10_bg_00000001.raw
bright_image_filename = Z:\PRODUCTS\XRAY\KeckPAD\IHEP_Testing\run-tuesday11\frames\tuesday11_00000001.raw

# Mask files generated by a previous program
dark_mask = Z:\PRODUCTS\XRAY\KeckPAD\IHEP_Testing\dark_pixels.pgm
hot_mask = Z:\PRODUCTS\XRAY\KeckPAD\IHEP_Testing\hot_pixels.pgm
