function pgm_write_stack(raster, pgm_filename, num_caps)
  pgm_file = fopen(pgm_filename, 'wb');

  ## Print the header per mmpad_bad_pixel_map_creation.md
  fprintf(pgm_file, "P5\n# Generated by Octave\n%i %i\n255\n", size(raster)(2),size(raster)(1));

  ## Convert the raster to the mask format
  mod_raster = uint8(isnan(raster)); # Collapse to ints

  for cap_idx=1:num_caps
    fwrite(pgm_file, mod_raster(:,:,cap_idx)', 'uint8', 'b'); #Big-endian per PGM standard, although redundant since the pixels are one byte
  endfor
  fclose(pgm_file);
  return
endfunction
