# All config files should have a "Default" section, although section is ignored in this file

[Default]
[ImageParams]
asic_width = 128
asic_height = 128
img_width = 512
img_height = 512
num_caps = 8
max_frames = 1001

#Keck
file_offset = 256
file_gap = 1024
bpp = 16

##MMPAD
#file_offset = 256
#file_gap = 2048
#bpp = 32

[Sensor Params]
#How many images at the start of a run to skip
num_skip_images = 2

[Analysis Params]
gain_threshold = 0.001

# Edge pixels to ignore for analysis, not map calculation
x_margin = 3
y_margin = 3

#Short Background File for read noise and pedestal
short_dark_image_filename = /home/sydor/projects/PAD_Analysis2/xpad_corrections/aps10-20260311/set-ee_11mar2026_RN/run-run1/frames/run1_00000001.raw
short_dark_image_filename = /home/sydor/projects/PAD_Analysis2/xpad_corrections/aps10-20260311/set-ee_11mar26_ff/run-B50_1/frames/B50_1_00000001.raw
#Long Background File for dark current
long_dark_image_filename = /home/sydor/projects/PAD_Analysis2/xpad_corrections/aps10/run-B50_/frames/B50ms_2_00000001.raw
#Foreground File
bright_image_filename = /home/sydor/projects/PAD_Analysis2/xpad_corrections/aps10-20260311/set-ee_11mar26_ff/run-F50_2/frames/F50_2_00000001.raw
# Keck llnl020
#dark_image_filename = /home/sydor/projects/PAD_Analysis2/run-feb-26-2024-bg-geocor-pinhole-3/frames/feb-26-2024-bg-geocor-pinhole-3_00000001.raw
#bright_image_filename = /home/sydor/projects/PAD_Analysis2/run-feb-26-2024-ff-fg-3/frames/feb-26-2024-ff-fg-3_00000001.raw


# Mask files generated by a previous program
dark_mask = aps10-corr-20260311/standard/dark_pixels.pgm
hot_mask = aps10-corr-20260311/standard/hot_pixels.pgm
ff_map = aps10-corr-20260311/standard/flatfield.raw

[Characterization]
do_dark_analysis = false
do_dark_current = false
do_read_noise = false
do_flatness = true
